# Generated by Django 3.2.5 on 2021-11-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_status', models.CharField(choices=[('A', 'Availed'), ('B', 'Booked'), ('C1', 'Cancelled by user'), ('C2', 'Cancelled by hotel')], max_length=2)),
                ('check_in_date', models.CharField(max_length=15)),
                ('check_out_date', models.CharField(max_length=15)),
                ('check_in_time', models.CharField(max_length=15)),
                ('check_out_time', models.CharField(max_length=15)),
                ('total_guests', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('booking_date', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.CharField(max_length=255)),
                ('owner_contact_no', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPriceDetails',
            fields=[
                ('room_type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price_per_day', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.hoteldetails')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('room_key', models.AutoField(primary_key=True, serialize=False)),
                ('room_no', models.PositiveIntegerField(null=True)),
                ('layout', models.CharField(max_length=40)),
                ('floor_no', models.PositiveIntegerField(default=0)),
                ('nru', models.CharField(max_length=255)),
                ('room_status', models.CharField(max_length=1)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bookingdetails')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.guestdetails')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.hoteldetails')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.roompricedetails')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountDetails',
            fields=[
                ('discount_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('month_valid', models.CharField(max_length=4)),
                ('length_of_stay', models.CharField(max_length=16)),
                ('offer_percent', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.hoteldetails')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.roompricedetails')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountAvailed',
            fields=[
                ('availed_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.discountdetails')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.guestdetails')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.hoteldetails')),
            ],
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.discountdetails'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.guestdetails'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.hoteldetails'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.roompricedetails'),
        ),
    ]
